name: dnb
description: A platform-agnostic Dart client library for interacting with DNB's Open Banking APIs.
version: 1.3.0
homepage: https://github.com/arnemolland/dart-dnb

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  http: ^0.12.0+4
  equatable: ^1.1.1
  json_serializable: ^3.2.5

dev_dependencies:
  test: ^1.14.2
  pedantic: ^1.9.0
  dotenv: ^2.0.0
  build_runner: ^1.8.0
